name: Monitor tronweb & tronbox NPM Updates

on:
  schedule:
    - cron: "*/10 * * * *" # Run every 10 minutes.
  workflow_dispatch:

jobs:
  check-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Run NPM monitor script
        run: node scripts/npm-monitor.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Commit updated version record
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add pkgVersions.json
          git commit -m 'update tron package versions' || echo "no changes"
          git push || echo "no changes"
